### POST request to example server
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "gotaga@gmail.com",
  "password": "Azerty2@"
}

###

POST http://localhost:3000/auth/register #
Content-Type: application/json

{
  "username": "bisho",
  "email": "bisho@gmail.com",
  "password": "ybb7@hbbbUH"
}

